# Generated by Django 5.1.4 on 2025-01-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Drugs'},
        ),
    ]
